name: Sync V2Ray configs to Pages
on:
  schedule:
    - cron:  '*/15 * * * *'   # هر ۱۵ دقیقه
  workflow_dispatch:           # امکان اجرای دستی
jobs:
  update:
    permissions:
      contents: write          # اجازهٔ Push با GITHUB_TOKEN
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Download latest configs
        run: curl -L \
          https://raw.githubusercontent.com/barry-far/V2ray-Config/main/All_Configs_Sub.txt \
          -o configs.txt
      - name: Commit if changed
        run: |
          if git diff --quiet configs.txt; then
            echo "No update";
          else
            git config user.name  "github-actions"
            git config user.email "actions@github.com"
            git commit -am "auto: update configs"
            git push
          fi
